sudo: required
language: java
jdk: oraclejdk8

before_install:
  - cd server-app  
  - export CODACY_PROJECT_TOKEN=lpfcu2z1ObDQljn3APCU
  - apt-get install jq  
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - mvn -N io.takari:maven:wrapper
  - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V    
  - mvn test

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
