sudo: required

matrix:
  include:
    - language: java
      jdk: oraclejdk8
      env:
        global:
          - CODECOV_TOKEN="1de6a879-f36f-4085-a69a-8c7247acd44c"
      before_install:
        - cd server-app 
        - mvn -N io.takari:maven:wrapper
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        
    - language: node_js
      node_js: stable      
      before_install:
        - cd client-app 
        - npm install -g @angular/cli
      install:
        - npm install
      script:
        - npm run build
      deploy:
        provider: HEROKU
        api_key:
          secure: c705175d-406f-42cc-8ac5-3d2aaa838c87 
        app: ticketreservation

